-- Create "invitations" table
CREATE TABLE `ruline`.`invitations` (`id` char(30) NOT NULL, `organization_id` char(30) NOT NULL, `user_id` varchar(30) NOT NULL, `member_id` char(30) NOT NULL, `status` enum('created','accepted','declined') NOT NULL DEFAULT 'created', `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), `updated_at` timestamp NOT NULL DEFAULT (current_timestamp()) ON UPDATE current_timestamp(), PRIMARY KEY (`id`), INDEX `idx_invitations_user_id_status` (`user_id`, `status`), INDEX `invitation_member_id` (`member_id`), INDEX `invitation_organization_id` (`organization_id`)) COLLATE utf8mb4_uca1400_ai_ci;
-- Create "members" table
CREATE TABLE `ruline`.`members` (`id` char(30) NOT NULL, `user_id` char(30) NOT NULL, `organization_id` char(30) NOT NULL, `role` enum('owner','admin','editor','viewer','member') NOT NULL DEFAULT 'member', `status` enum('active','left','removed','invited','declined') NOT NULL DEFAULT 'active', `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), `updated_at` timestamp NOT NULL DEFAULT (current_timestamp()) ON UPDATE current_timestamp(), PRIMARY KEY (`id`), INDEX `idx_members_organization_id` (`organization_id`), UNIQUE INDEX `idx_members_user_id_status` (`user_id`, `status`)) COLLATE utf8mb4_uca1400_ai_ci;
-- Create "organizations" table
CREATE TABLE `ruline`.`organizations` (`id` char(30) NOT NULL, `name` varchar(255) NOT NULL, `status` enum('active') NOT NULL DEFAULT 'active', `logo` varchar(255) NOT NULL, `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), `updated_at` timestamp NOT NULL DEFAULT (current_timestamp()) ON UPDATE current_timestamp(), PRIMARY KEY (`id`)) COLLATE utf8mb4_uca1400_ai_ci;
-- Create "projects" table
CREATE TABLE `ruline`.`projects` (`id` char(30) NOT NULL, `organization_id` char(30) NOT NULL, `name` varchar(255) NOT NULL, `status` enum('active') NOT NULL DEFAULT 'active', `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), `updated_at` timestamp NOT NULL DEFAULT (current_timestamp()) ON UPDATE current_timestamp(), PRIMARY KEY (`organization_id`, `id`)) COLLATE utf8mb4_uca1400_ai_ci;
-- Create "users" table
CREATE TABLE `ruline`.`users` (`id` char(30) NOT NULL, `email` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `status` enum('created','active') NOT NULL DEFAULT 'created', `avatar` varchar(255) NOT NULL, `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), `updated_at` timestamp NOT NULL DEFAULT (current_timestamp()) ON UPDATE current_timestamp(), `last_login` timestamp NOT NULL DEFAULT (current_timestamp()), PRIMARY KEY (`id`), UNIQUE INDEX `idx_users_email` (`email`)) COLLATE utf8mb4_uca1400_ai_ci;
-- Create "workflows" table
CREATE TABLE `ruline`.`workflows` (`id` char(30) NOT NULL, `organization_id` char(30) NOT NULL, `project_id` char(30) NOT NULL, `name` varchar(255) NOT NULL, `status` enum('active','archived') NOT NULL DEFAULT 'active', `active_version` mediumint unsigned NULL, `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), `updated_at` timestamp NOT NULL DEFAULT (current_timestamp()) ON UPDATE current_timestamp(), PRIMARY KEY (`organization_id`, `project_id`, `id`), INDEX `idx_workflows_organization_id` (`organization_id`, `id`, `status`), INDEX `workflow_active_version` (`organization_id`, `project_id`, `id`, `active_version`)) COLLATE utf8mb4_uca1400_ai_ci;
-- Create "workflow_versions" table
CREATE TABLE `ruline`.`workflow_versions` (`organization_id` char(30) NOT NULL, `project_id` char(30) NOT NULL, `workflow_id` char(30) NOT NULL, `version` mediumint unsigned NOT NULL, `status` enum('draft','in_review','published','archived') NOT NULL DEFAULT 'draft', `definition` json NOT NULL, `created_at` timestamp NOT NULL DEFAULT (current_timestamp()), `updated_at` timestamp NOT NULL DEFAULT (current_timestamp()) ON UPDATE current_timestamp(), PRIMARY KEY (`organization_id`, `project_id`, `workflow_id`, `version`), INDEX `idx_workflow_versions_workflow_id_version` (`workflow_id`, `version`, `status`)) COLLATE utf8mb4_uca1400_ai_ci;
-- Modify "invitations" table
ALTER TABLE `ruline`.`invitations` ADD CONSTRAINT `invitation_member_id` FOREIGN KEY (`member_id`) REFERENCES `ruline`.`members` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT `invitation_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `ruline`.`organizations` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT `invitation_user_id` FOREIGN KEY (`user_id`) REFERENCES `ruline`.`users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "members" table
ALTER TABLE `ruline`.`members` ADD CONSTRAINT `member_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `ruline`.`organizations` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT `member_user_id` FOREIGN KEY (`user_id`) REFERENCES `ruline`.`users` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "projects" table
ALTER TABLE `ruline`.`projects` ADD CONSTRAINT `project_organization_id` FOREIGN KEY (`organization_id`) REFERENCES `ruline`.`organizations` (`id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "workflows" table
ALTER TABLE `ruline`.`workflows` ADD CONSTRAINT `workflow_active_version` FOREIGN KEY (`organization_id`, `project_id`, `id`, `active_version`) REFERENCES `ruline`.`workflow_versions` (`organization_id`, `project_id`, `workflow_id`, `version`) ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT `workflow_project_id` FOREIGN KEY (`organization_id`, `project_id`) REFERENCES `ruline`.`projects` (`organization_id`, `id`) ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "workflow_versions" table
ALTER TABLE `ruline`.`workflow_versions` ADD CONSTRAINT `workflow_version_workflow_id` FOREIGN KEY (`organization_id`, `project_id`, `workflow_id`) REFERENCES `ruline`.`workflows` (`organization_id`, `project_id`, `id`) ON UPDATE NO ACTION ON DELETE CASCADE;
