[package]
name    = "ruline-context"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
license.workspace = true
readme.workspace  = true


[dependencies]
dashmap    = { workspace = true }
serde_json = { workspace = true }
