name: Rust Setup
inputs:
  github_token:
    description: 'GitHub Token, usually ${{ secrets.GITHUB_TOKEN }}'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Setup Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ inputs.shared-cache-key }}
        key: ${{ inputs.cache-key }}
        save-if: ${{ github.ref == 'refs/heads/main' || 'false' }}
